export const DB_FETCH = "DB_FETCH";
export const DB_FETCH_SUCCESS = "DB_FETCH_SUCCESS";
export const DB_FETCH_FAILED = "DB_FETCH_FAILED";

export const DB_ADD_NEW_ENTRY = "DB_ADD_NEW_ENTRY";
export const DB_ADD_NEW_ENTRY_SUCCESS = "DB_ADD_NEW_ENTRY_SUCCESS";
export const DB_ADD_NEW_ENTRY_FAILED = "DB_ADD_NEW_ENTRY_FAILED";

export const DB_EDIT_ITEM = "DB_EDIT_ITEM";
export const DB_EDIT_ITEM_SUCCESS = "DB_EDIT_ITEM_SUCCESS";
export const DB_EDIT_ITEM_FAILED = "DB_EDIT_ITEM_FAILED";
export const DB_SET_ERROR = "DB_SET_ERROR";

export const SET_LOADING = "SET_LOADING";
export const ON_FIND_TICKETS = "ON_FIND_TICKETS";


